version: '3'
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: maxplayer_node
    volumes:
        - .:/usr/src/app
    working_dir: /usr/src/app
    network_mode: host
    tty: true