service: google-music

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  stage: dev
  region: eu-central-1
  environment:
    foo: 123

functions:
  spotifySearchAll:
    name: spotify-search-all
    handler: handler.spotifySearchAll
    events:
      - http:
          path: spotify/search-all
          method: get
          cors: true
  googleMusicGetStream:
    name: google-music-get-stream
    handler: handler.googleMusicGetStream
    events:
      - http:
          path: googlemusic/stream
          method: get
          cors: true